sudo: required
services:
  - docker

before_install:
  - docker build -t doronma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true doronma/react-test npm test

after_success:
  - docker build -t doroncomputer/multi-client ./client
  - docker build -t doroncomputer/multi-nginx ./nginx
  - docker build -t doroncomputer/multi-worker ./worker
  - docker build -t doroncomputer/multi-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push doroncomputer/multi-client
  - docker push doroncomputer/multi-nginx
  - docker push doroncomputer/multi-worker
  - docker push doroncomputer/multi-server

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-867433151820"
  backet_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
